### ISSUE TITLE
Insert font.css into critical-css/webfont.css

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-font-optimization#4]
I enabled 

Critical CSS | To prevent a Flash of Unstyled Text (FOUT, FOIT or FOFT) you can include the font CSS in the Critical CSS.

but I did not find a way to properly extract the font css. It would be nice if that would be available in the critical css plugin.

**Comment by optimalisatie** [comment]
For Google fonts, this feature is available in the Web Font Optimization plugin. For other fonts it would require advanced / custom techniques for each font. 

In the Google Font Downloader, when you select `Display @font-face CSS` you will see the CSS that you can insert directly into the critical CSS.

![image](https://user-images.githubusercontent.com/8843669/42595318-36a5a6a2-8552-11e8-8bc8-09da55971ea1.png)

On the Font Optimization settings page you can find a link to create / edit the webfont Critical CSS file.

![image](https://user-images.githubusercontent.com/8843669/42595266-0802e9fe-8552-11e8-913a-bb8b5f4a9737.png)

More information can also be found in the Google article about `font-display` optimization. It is advised to learn this technique as it is often a critical aspect of the Google Lighthouse score.

https://developers.google.com/web/updates/2016/02/font-display

**Comment by AlphaDE** [comment]
Gotcha... recommend to put a hint there, where to find the critical CSS when the Google font downloader is used, an amendment of the existing description would do the job.

Just the first two sentences of your answer :)
